language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  - S_KEY = "sndjnqfknfjdnunq8866j"
# command to run tests
script:
  - chmod +x manage.py
  - ./manage.py test search
  - ./manage.py test account