language: python
python:
  - "3.8"


before_install:
- sudo apt-get install xvfb
- wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
- sudo tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C /usr/bin
- sudo chmod a+x /usr/bin/geckodriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5 # give xvfb some time to start

# command to install dependencies
install:
  - pip install -r requirements.txt


addons:
  - firefox: "56.0"

services:
  - postgresql

# command to run tests
script:
  - chmod +x manage.py
  - ./manage.py test search
  - ./manage.py test account